name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Specify Flutter version
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build web
        run: flutter build web --release --base-href "/energy-game-UI/" --dart-define=API_URL=https://energy-game-api-6a18fc829f3d.herokuapp.com/
        
      # Add this step to create .nojekyll file
      - name: Add .nojekyll file
        run: touch ./build/web/.nojekyll
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
